export class SVGDataList {
    list: SVGList = {};

    append = (data: SVGData) => {
        if (!data) console.log(data)
        const {camel, hyphen} = data.name;
        const {attributes, children} = data.element;
        const item = {
            [camel]: {
                name: hyphen,
                attributes,
                children
            }
        };
        this.list = {...this.list, ...item}
    }
}

export const WARNING_COMMENT: string = `/*
*   DO NOT MAKE CHANGES TO THIS FILE 
*   THIS FILE WAS GENERATED BY REACT-SCRIPTS-SVG
*   https://github.com/wllkle/react-scripts-svg
*/\n\n`;
