export const WARNING_COMMENT: string = `/*
*   DO NOT MAKE CHANGES TO THIS FILE
*   THIS FILE WILL BE OVERWRITTEN
*   GENERATED BY REACT-SVGS
*   https://github.com/wllkle/react-svgs
*/`;

export const COMPONENT_LINK: string = "https://reactjs.org/docs/jsx-in-depth.html#user-defined-components-must-be-capitalized";

export const BANNER: string = `\n██████  ███████  ██████   ██████ ████████    ███████ ██     ██  ██████  ███████
██   ██ ██      ██    ██ ██         ██       ██      ██     ██ ██       ██
██████  █████   ████████ ██         ██ █████ ███████ ██     ██ ██   ███ ███████
██   ██ ██      ██    ██ ██         ██            ██  ██   ██  ██    ██      ██
██   ██ ███████ ██    ██  ██████    ██       ███████   █████    ██████  ███████\n`;
