import {IIconList} from "./interfaces";

const clean = (obj: IIconList): string => {
    const cleaned = JSON.stringify(obj, null, 4);
    return cleaned.replace(/^[\t ]*"[^:\n\r]+(?<!\\)":/gm, match => {
        return match.replace(/"/g, "");
    });
};

const warningComment: string = `/*
*   DO NOT MAKE CHANGES TO THIS FILE 
*   THIS FILE WAS GENERATED BY REACT-SCRIPTS-SVG
*   https://github.com/wllkle/react-scripts-svg
*/`;

export const getTemplate = (
    content: IIconList,
    name: string,
    typescript: boolean,
    propTypes: boolean
): string => {
    const ts = (value: string) => typescript ? value : "";

    return `${warningComment}${ts("\n\n// @ts-nocheck")}

import React${ts(", {ReactNode, CSSProperties}")} from "react";${propTypes ? `\nimport PropTypes from "prop-types";` : ""}
import {data${propTypes ? `, ${name}TypesArray` : ""}${ts(`, ${name}Types, INode`)}} from "./types";

${ts(`\ninterface ${name}Props {
    name: ${name}Types,
    className?: string,
    style?: CSSProperties
}`)}

export const ${name} = (props${ts(`: ${name}Props`)}) => {
    const {name, className = undefined, style = undefined} = props;
    const iconData = data[name] ? data[name] : undefined;
    const {viewBox, element} = iconData || {};

    const svgProps = {
        ...(className) && {className},
        ...(style) && {style},
        ...(viewBox) && {viewBox},
        ...(element) && {children: renderChildNodes(element)}
    };
    
    return (
        <svg {...svgProps}/>
    );
}${propTypes ? `\n\n${name}${getPropTypes}` : ""}

const renderChildNodes = (nodes${ts(": INode[]")}): ReactNode => (
    <>
        {nodes.map((node${ts(": INode")}) => {
            const {name, attributes, type, value, children} = node;
            const Tag = name.toString();
            const id = Math.random().toString(36);

            if (type === "print") return (<Tag key={id}>{value}</Tag>);

            return (<Tag key={id} {...attributes}>{renderChildNodes(children)}</Tag>);
        })}
    </>
);

export default ${name};
export {${name}TypesArray} from "./defs";${ts(`\nexport type {${name}Types} from "./defs";`)}
`;
}

const getPropTypes: string = `.propTypes = {
    name: PropTypes.oneOf(IconTypesArray),
    className: PropTypes.string,
    style: PropTypes.object
}`

export const getTypesTemplate = (content: IIconList, name: string, typescript: boolean) => {
    const list = clean(content)
    const iconTypes = Object.keys(content).map(key => `"${key}"`)
    const iconTypesArray = iconTypes.join(",\n\t")

    if (typescript) {
        const iconTypesUnion = iconTypes.join(" |\n\t")

        return `export interface INode {
    name: string,
    type: string,
    value?: string,
    attributes: object,
    children: INode[]
}

interface I${name}Data {
    [key: string]: {
        name: string,
        viewBox: string,
        element: INode[]
    }
}

export const data: I${name}Data = ${list};
        
export type ${name}Types = ${iconTypesUnion};

export const ${name}TypesArray: string[] = [
    ${iconTypesArray}
];
`;
    }

    return `export const data = ${list};
    
export const ${name}TypesArray = [
    ${iconTypesArray}
];
`;
}
